export default defineEventHandler(() => {
  return [
    {
      id: '1',
      name: '计算机网络信息中心',
      code: '241711',
      parentId: null,
      parentName: '中国科学院',
      isActive: true,
      order: 0,
      isIndependentTraining: true,
      isVirtual: false,
      children: [
        {
          id: '1-1',
          name: '大数据技术与应用发展部',
          code: '241711001',
          parentId: '1',
          parentName: '计算机网络信息中心',
          isActive: true,
          order: 1,
          isIndependentTraining: false,
          isVirtual: false,
          children: [
            {
              id: '1-1-1',
              name: '党群办公室',
              code: '241711001001',
              parentId: '1-1',
              parentName: '大数据技术与应用发展部',
              isActive: true,
              order: 1,
              isIndependentTraining: false,
              isVirtual: false,
            },
          ],
        },
        {
          id: '1-2',
          name: '高性能计算技术与应用发展部',
          code: '241711002',
          parentId: '1',
          parentName: '计算机网络信息中心',
          isActive: true,
          order: 2,
          isIndependentTraining: false,
          isVirtual: false,
        },
        {
          id: '1-3',
          name: '管理信息化技术与应用发展部',
          code: '241711003',
          parentId: '1',
          parentName: '计算机网络信息中心',
          isActive: true,
          order: 3,
          isIndependentTraining: false,
          isVirtual: false,
          children: [
            {
              id: '1-3-1',
              name: '广州中心',
              code: '241711003001',
              parentId: '1-3',
              parentName: '管理信息化技术与应用发展部',
              isActive: true,
              order: 1,
              isIndependentTraining: false,
              isVirtual: false,
            },
            {
              id: '1-3-2',
              name: '基地办公室',
              code: '241711003002',
              parentId: '1-3',
              parentName: '管理信息化技术与应用发展部',
              isActive: true,
              order: 2,
              isIndependentTraining: false,
              isVirtual: false,
            },
          ],
        },
      ],
    },
  ]
})

