// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/401': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/401').default>>>>
    }
    '/403': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/403').default>>>>
    }
    '/500': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/500').default>>>>
    }
    '/': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/index').default>>>>
    }
    '/list/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/list/[id].delete').default>>>>
    }
    '/list/basic-list': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/list/basic-list.post').default>>>>
    }
    '/list/consult-list': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/list/consult-list.post').default>>>>
    }
    '/list/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/list/create.post').default>>>>
    }
    '/list/crud-table': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/list/crud-table.post').default>>>>
    }
    '/list': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/list/index.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/list/index.put').default>>>>
    }
    '/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/login.post').default>>>>
    }
    '/logout': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/logout').default>>>>
    }
    '/menu': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/menu/index').default>>>>
    }
    '/organization/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/organization/[id].get').default>>>>
    }
    '/organization/tree': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/organization/tree').default>>>>
    }
    '/personnel/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/personnel/[id].get').default>>>>
    }
    '/personnel/:id/status': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/personnel/[id]/status.put').default>>>>
    }
    '/personnel/list': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/personnel/list.post').default>>>>
    }
    '/role-assignment/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/role-assignment/[id].get').default>>>>
    }
    '/role-assignment/batch-delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/role-assignment/batch-delete.post').default>>>>
    }
    '/role-assignment/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/role-assignment/create.post').default>>>>
    }
    '/role-assignment/list': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/role-assignment/list.post').default>>>>
    }
    '/role/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/role/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/role/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/role/[id].put').default>>>>
    }
    '/role/:id/permissions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/role/[id]/permissions.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/role/[id]/permissions.post').default>>>>
    }
    '/role/:id/status': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/role/[id]/status.put').default>>>>
    }
    '/role/batch-delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/role/batch-delete.post').default>>>>
    }
    '/role/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/role/create.post').default>>>>
    }
    '/role/list': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/role/list.post').default>>>>
    }
    '/test': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/test.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/test.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/test.put').default>>>>
    }
    '/user/info': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/user/info').default>>>>
    }
  }
}
export {}